# Generated by Django 3.2.11 on 2022-01-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'RECENTLY'), ('MW', 'MOST WATCHES'), ('TR', 'TOP RATED'), ('comingsoon', 'COMING SOON')], max_length=10),
        ),
    ]
