# Generated by Django 3.2.11 on 2022-01-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'RECENTLY'), ('MW', 'MOST WATCHES'), ('TR', 'TOP RATED'), ('CS', 'COMING SOON')], max_length=2),
        ),
    ]
